import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { getPool } from "@/integrations/postgres/client.server";
import { withUser } from "@/integrations/postgres/query.server";

let tableEnsured = false;
async function ensureNotebookTable() {
  if (tableEnsured) return;
  try {
    await getPool().query(`
      CREATE TABLE IF NOT EXISTS public.notebook_notes (
        id uuid PRIMARY KEY,
        user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
        title text NOT NULL DEFAULT '',
        content text NOT NULL DEFAULT '',
        tags text[] NOT NULL DEFAULT '{}',
        color text NOT NULL DEFAULT 'slate',
        is_pinned boolean NOT NULL DEFAULT false,
        images jsonb NOT NULL DEFAULT '[]'::jsonb,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now()
      );
      CREATE INDEX IF NOT EXISTS idx_notebook_notes_user ON public.notebook_notes(user_id, updated_at DESC);
      ALTER TABLE public.notebook_notes ENABLE ROW LEVEL SECURITY;
      DROP POLICY IF EXISTS "Users manage own notebook notes" ON public.notebook_notes;
      CREATE POLICY "Users manage own notebook notes" ON public.notebook_notes
        FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
      GRANT SELECT, INSERT, UPDATE, DELETE ON public.notebook_notes TO authenticated;
      CREATE TABLE IF NOT EXISTS public.notebook_seeded (
        user_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
        seeded_at timestamptz NOT NULL DEFAULT now()
      );
      ALTER TABLE public.notebook_seeded ENABLE ROW LEVEL SECURITY;
      DROP POLICY IF EXISTS "Users manage own notebook seed flag" ON public.notebook_seeded;
      CREATE POLICY "Users manage own notebook seed flag" ON public.notebook_seeded
        FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
      GRANT SELECT, INSERT, UPDATE, DELETE ON public.notebook_seeded TO authenticated;
    `);
    tableEnsured = true;
  } catch (err) {
    console.warn("[notebook] ensure table check:", (err as Error).message);
  }
}

const noteSchema = z.object({
  id: z.string().uuid(),
  title: z.string(),
  content: z.string(),
  tags: z.array(z.string()),
  color: z.enum(["slate", "indigo", "emerald", "amber", "rose", "cyan", "purple"]),
  isPinned: z.boolean(),
  images: z.array(z.string()),
  createdAt: z.string().optional(),
});

const DEFAULT_NOTE_TITLE = "Welcome to your Notebook";
const DEFAULT_NOTE_CONTENT =
  "<p>Jot down ideas, meeting notes and reminders here. Everything saves automatically — edit or delete this note anytime.</p>";

const COLUMNS = `id, title, content, tags, color, is_pinned as "isPinned", images,
  created_at::text as "createdAt", updated_at::text as "updatedAt"`;

export const listNotebookNotesFn = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    await ensureNotebookTable();
    return withUser(context.userId, async (client) => {
      // First-login seeding: the flag row is inserted once per user, so the default
      // note is never recreated after the user edits or deletes it. Users who
      // already have notes just get the flag (their notes stay untouched).
      const first = await client.query(
        `INSERT INTO public.notebook_seeded (user_id) VALUES ($1) ON CONFLICT (user_id) DO NOTHING RETURNING user_id`,
        [context.userId]
      );
      if (first.rowCount) {
        await client.query(
          `INSERT INTO public.notebook_notes (id, user_id, title, content, tags, color, is_pinned, images)
           SELECT gen_random_uuid(), $1::uuid, $2::text, $3::text, ARRAY['welcome'], 'indigo', false, '[]'::jsonb
           WHERE NOT EXISTS (SELECT 1 FROM public.notebook_notes WHERE user_id = $1)`,
          [context.userId, DEFAULT_NOTE_TITLE, DEFAULT_NOTE_CONTENT]
        );
      }
      const res = await client.query(
        `SELECT ${COLUMNS} FROM public.notebook_notes WHERE user_id = $1 ORDER BY updated_at DESC`,
        [context.userId]
      );
      return res.rows;
    });
  });

/** Insert-or-update one note (id is generated by the client). */
export const upsertNotebookNoteFn = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .validator((d: z.infer<typeof noteSchema>) => noteSchema.parse(d))
  .handler(async ({ data, context }) => {
    await ensureNotebookTable();
    return withUser(context.userId, async (client) => {
      const res = await client.query(
        `INSERT INTO public.notebook_notes
           (id, user_id, title, content, tags, color, is_pinned, images, created_at, updated_at)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8::jsonb, COALESCE($9::timestamptz, now()), now())
         ON CONFLICT (id) DO UPDATE SET
           title = EXCLUDED.title,
           content = EXCLUDED.content,
           tags = EXCLUDED.tags,
           color = EXCLUDED.color,
           is_pinned = EXCLUDED.is_pinned,
           images = EXCLUDED.images,
           updated_at = now()
         WHERE public.notebook_notes.user_id = EXCLUDED.user_id
         RETURNING ${COLUMNS}`,
        [
          data.id,
          context.userId,
          data.title,
          data.content,
          data.tags,
          data.color,
          data.isPinned,
          JSON.stringify(data.images),
          data.createdAt ?? null,
        ]
      );
      return res.rows[0] ?? null;
    });
  });

export const deleteNotebookNoteFn = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .validator((d: { id: string }) => z.object({ id: z.string().uuid() }).parse(d))
  .handler(async ({ data, context }) => {
    await ensureNotebookTable();
    await withUser(context.userId, (client) =>
      client.query(`DELETE FROM public.notebook_notes WHERE id = $1 AND user_id = $2`, [
        data.id,
        context.userId,
      ])
    );
    return { success: true };
  });

export const clearNotebookNotesFn = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    await ensureNotebookTable();
    await withUser(context.userId, (client) =>
      client.query(`DELETE FROM public.notebook_notes WHERE user_id = $1`, [context.userId])
    );
    return { success: true };
  });
