/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkloadRouteImport } from './routes/_authenticated/workload'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSyncRouteImport } from './routes/_authenticated/sync'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPlanningSuggestionsRouteImport } from './routes/_authenticated/planning-suggestions'
import { Route as AuthenticatedPlanningRouteImport } from './routes/_authenticated/planning'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMyDayRouteImport } from './routes/_authenticated/my-day'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedIntelligenceRouteImport } from './routes/_authenticated/intelligence'
import { Route as AuthenticatedHeatmapRouteImport } from './routes/_authenticated/heatmap'
import { Route as AuthenticatedForecastRouteImport } from './routes/_authenticated/forecast'
import { Route as AuthenticatedExportsRouteImport } from './routes/_authenticated/exports'
import { Route as AuthenticatedExecutiveRouteImport } from './routes/_authenticated/executive'
import { Route as AuthenticatedEodTasksRouteImport } from './routes/_authenticated/eod-tasks'
import { Route as AuthenticatedEodRouteImport } from './routes/_authenticated/eod'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfigureRouteImport } from './routes/_authenticated/configure'
import { Route as AuthenticatedCommandRouteImport } from './routes/_authenticated/command'
import { Route as AuthenticatedBlockersRouteImport } from './routes/_authenticated/blockers'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiStorageUploadRouteImport } from './routes/api/storage/upload'
import { Route as ApiStorageFileRouteImport } from './routes/api/storage/file'
import { Route as AuthenticatedSettingsOperationsRouteImport } from './routes/_authenticated/settings.operations'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings.notifications'
import { Route as AuthenticatedConfigureNewRouteImport } from './routes/_authenticated/configure.new'
import { Route as AuthenticatedConfigureAutomationsRouteImport } from './routes/_authenticated/configure.automations'
import { Route as ApiPublicHooksWorkloadSnapshotRouteImport } from './routes/api/public/hooks/workload-snapshot'
import { Route as ApiPublicHooksPlanningSuggestionsRouteImport } from './routes/api/public/hooks/planning-suggestions'
import { Route as ApiPublicHooksMorningDigestRouteImport } from './routes/api/public/hooks/morning-digest'
import { Route as ApiPublicHooksGenerateNudgesRouteImport } from './routes/api/public/hooks/generate-nudges'
import { Route as ApiPublicHooksEveningDigestRouteImport } from './routes/api/public/hooks/evening-digest'
import { Route as ApiPublicHooksDetectRisksRouteImport } from './routes/api/public/hooks/detect-risks'
import { Route as ApiPublicHooksCarryForwardRouteImport } from './routes/api/public/hooks/carry-forward'
import { Route as ApiPublicHooksAutomationTickRouteImport } from './routes/api/public/hooks/automation-tick'
import { Route as ApiPublicHooksAutomationDueEnqueueRouteImport } from './routes/api/public/hooks/automation-due-enqueue'
import { Route as ApiPublicHooksAdoptionRollupRouteImport } from './routes/api/public/hooks/adoption-rollup'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkloadRoute = AuthenticatedWorkloadRouteImport.update({
  id: '/workload',
  path: '/workload',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSyncRoute = AuthenticatedSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanningSuggestionsRoute =
  AuthenticatedPlanningSuggestionsRouteImport.update({
    id: '/planning-suggestions',
    path: '/planning-suggestions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlanningRoute = AuthenticatedPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyDayRoute = AuthenticatedMyDayRouteImport.update({
  id: '/my-day',
  path: '/my-day',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntelligenceRoute =
  AuthenticatedIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHeatmapRoute = AuthenticatedHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedForecastRoute = AuthenticatedForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExportsRoute = AuthenticatedExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExecutiveRoute = AuthenticatedExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEodTasksRoute = AuthenticatedEodTasksRouteImport.update({
  id: '/eod-tasks',
  path: '/eod-tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEodRoute = AuthenticatedEodRouteImport.update({
  id: '/eod',
  path: '/eod',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfigureRoute = AuthenticatedConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommandRoute = AuthenticatedCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBlockersRoute = AuthenticatedBlockersRouteImport.update({
  id: '/blockers',
  path: '/blockers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiStorageUploadRoute = ApiStorageUploadRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageFileRoute = ApiStorageFileRouteImport.update({
  id: '/api/storage/file',
  path: '/api/storage/file',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsOperationsRoute =
  AuthenticatedSettingsOperationsRouteImport.update({
    id: '/settings/operations',
    path: '/settings/operations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfigureNewRoute =
  AuthenticatedConfigureNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedConfigureRoute,
  } as any)
const AuthenticatedConfigureAutomationsRoute =
  AuthenticatedConfigureAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedConfigureRoute,
  } as any)
const ApiPublicHooksWorkloadSnapshotRoute =
  ApiPublicHooksWorkloadSnapshotRouteImport.update({
    id: '/api/public/hooks/workload-snapshot',
    path: '/api/public/hooks/workload-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPlanningSuggestionsRoute =
  ApiPublicHooksPlanningSuggestionsRouteImport.update({
    id: '/api/public/hooks/planning-suggestions',
    path: '/api/public/hooks/planning-suggestions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMorningDigestRoute =
  ApiPublicHooksMorningDigestRouteImport.update({
    id: '/api/public/hooks/morning-digest',
    path: '/api/public/hooks/morning-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateNudgesRoute =
  ApiPublicHooksGenerateNudgesRouteImport.update({
    id: '/api/public/hooks/generate-nudges',
    path: '/api/public/hooks/generate-nudges',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEveningDigestRoute =
  ApiPublicHooksEveningDigestRouteImport.update({
    id: '/api/public/hooks/evening-digest',
    path: '/api/public/hooks/evening-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDetectRisksRoute =
  ApiPublicHooksDetectRisksRouteImport.update({
    id: '/api/public/hooks/detect-risks',
    path: '/api/public/hooks/detect-risks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCarryForwardRoute =
  ApiPublicHooksCarryForwardRouteImport.update({
    id: '/api/public/hooks/carry-forward',
    path: '/api/public/hooks/carry-forward',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutomationTickRoute =
  ApiPublicHooksAutomationTickRouteImport.update({
    id: '/api/public/hooks/automation-tick',
    path: '/api/public/hooks/automation-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutomationDueEnqueueRoute =
  ApiPublicHooksAutomationDueEnqueueRouteImport.update({
    id: '/api/public/hooks/automation-due-enqueue',
    path: '/api/public/hooks/automation-due-enqueue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAdoptionRollupRoute =
  ApiPublicHooksAdoptionRollupRouteImport.update({
    id: '/api/public/hooks/adoption-rollup',
    path: '/api/public/hooks/adoption-rollup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/blockers': typeof AuthenticatedBlockersRoute
  '/command': typeof AuthenticatedCommandRoute
  '/configure': typeof AuthenticatedConfigureRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eod': typeof AuthenticatedEodRoute
  '/eod-tasks': typeof AuthenticatedEodTasksRoute
  '/executive': typeof AuthenticatedExecutiveRoute
  '/exports': typeof AuthenticatedExportsRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/heatmap': typeof AuthenticatedHeatmapRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/my-day': typeof AuthenticatedMyDayRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/planning-suggestions': typeof AuthenticatedPlanningSuggestionsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sync': typeof AuthenticatedSyncRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/today': typeof AuthenticatedTodayRoute
  '/workload': typeof AuthenticatedWorkloadRoute
  '/configure/automations': typeof AuthenticatedConfigureAutomationsRoute
  '/configure/new': typeof AuthenticatedConfigureNewRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/operations': typeof AuthenticatedSettingsOperationsRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/public/hooks/adoption-rollup': typeof ApiPublicHooksAdoptionRollupRoute
  '/api/public/hooks/automation-due-enqueue': typeof ApiPublicHooksAutomationDueEnqueueRoute
  '/api/public/hooks/automation-tick': typeof ApiPublicHooksAutomationTickRoute
  '/api/public/hooks/carry-forward': typeof ApiPublicHooksCarryForwardRoute
  '/api/public/hooks/detect-risks': typeof ApiPublicHooksDetectRisksRoute
  '/api/public/hooks/evening-digest': typeof ApiPublicHooksEveningDigestRoute
  '/api/public/hooks/generate-nudges': typeof ApiPublicHooksGenerateNudgesRoute
  '/api/public/hooks/morning-digest': typeof ApiPublicHooksMorningDigestRoute
  '/api/public/hooks/planning-suggestions': typeof ApiPublicHooksPlanningSuggestionsRoute
  '/api/public/hooks/workload-snapshot': typeof ApiPublicHooksWorkloadSnapshotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/blockers': typeof AuthenticatedBlockersRoute
  '/command': typeof AuthenticatedCommandRoute
  '/configure': typeof AuthenticatedConfigureRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eod': typeof AuthenticatedEodRoute
  '/eod-tasks': typeof AuthenticatedEodTasksRoute
  '/executive': typeof AuthenticatedExecutiveRoute
  '/exports': typeof AuthenticatedExportsRoute
  '/forecast': typeof AuthenticatedForecastRoute
  '/heatmap': typeof AuthenticatedHeatmapRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/my-day': typeof AuthenticatedMyDayRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/planning-suggestions': typeof AuthenticatedPlanningSuggestionsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sync': typeof AuthenticatedSyncRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/today': typeof AuthenticatedTodayRoute
  '/workload': typeof AuthenticatedWorkloadRoute
  '/configure/automations': typeof AuthenticatedConfigureAutomationsRoute
  '/configure/new': typeof AuthenticatedConfigureNewRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/operations': typeof AuthenticatedSettingsOperationsRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/public/hooks/adoption-rollup': typeof ApiPublicHooksAdoptionRollupRoute
  '/api/public/hooks/automation-due-enqueue': typeof ApiPublicHooksAutomationDueEnqueueRoute
  '/api/public/hooks/automation-tick': typeof ApiPublicHooksAutomationTickRoute
  '/api/public/hooks/carry-forward': typeof ApiPublicHooksCarryForwardRoute
  '/api/public/hooks/detect-risks': typeof ApiPublicHooksDetectRisksRoute
  '/api/public/hooks/evening-digest': typeof ApiPublicHooksEveningDigestRoute
  '/api/public/hooks/generate-nudges': typeof ApiPublicHooksGenerateNudgesRoute
  '/api/public/hooks/morning-digest': typeof ApiPublicHooksMorningDigestRoute
  '/api/public/hooks/planning-suggestions': typeof ApiPublicHooksPlanningSuggestionsRoute
  '/api/public/hooks/workload-snapshot': typeof ApiPublicHooksWorkloadSnapshotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/blockers': typeof AuthenticatedBlockersRoute
  '/_authenticated/command': typeof AuthenticatedCommandRoute
  '/_authenticated/configure': typeof AuthenticatedConfigureRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/eod': typeof AuthenticatedEodRoute
  '/_authenticated/eod-tasks': typeof AuthenticatedEodTasksRoute
  '/_authenticated/executive': typeof AuthenticatedExecutiveRoute
  '/_authenticated/exports': typeof AuthenticatedExportsRoute
  '/_authenticated/forecast': typeof AuthenticatedForecastRoute
  '/_authenticated/heatmap': typeof AuthenticatedHeatmapRoute
  '/_authenticated/intelligence': typeof AuthenticatedIntelligenceRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRoute
  '/_authenticated/my-day': typeof AuthenticatedMyDayRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/planning': typeof AuthenticatedPlanningRoute
  '/_authenticated/planning-suggestions': typeof AuthenticatedPlanningSuggestionsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sync': typeof AuthenticatedSyncRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/workload': typeof AuthenticatedWorkloadRoute
  '/_authenticated/configure/automations': typeof AuthenticatedConfigureAutomationsRoute
  '/_authenticated/configure/new': typeof AuthenticatedConfigureNewRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/operations': typeof AuthenticatedSettingsOperationsRoute
  '/api/storage/file': typeof ApiStorageFileRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/public/hooks/adoption-rollup': typeof ApiPublicHooksAdoptionRollupRoute
  '/api/public/hooks/automation-due-enqueue': typeof ApiPublicHooksAutomationDueEnqueueRoute
  '/api/public/hooks/automation-tick': typeof ApiPublicHooksAutomationTickRoute
  '/api/public/hooks/carry-forward': typeof ApiPublicHooksCarryForwardRoute
  '/api/public/hooks/detect-risks': typeof ApiPublicHooksDetectRisksRoute
  '/api/public/hooks/evening-digest': typeof ApiPublicHooksEveningDigestRoute
  '/api/public/hooks/generate-nudges': typeof ApiPublicHooksGenerateNudgesRoute
  '/api/public/hooks/morning-digest': typeof ApiPublicHooksMorningDigestRoute
  '/api/public/hooks/planning-suggestions': typeof ApiPublicHooksPlanningSuggestionsRoute
  '/api/public/hooks/workload-snapshot': typeof ApiPublicHooksWorkloadSnapshotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/analytics'
    | '/blockers'
    | '/command'
    | '/configure'
    | '/dashboard'
    | '/eod'
    | '/eod-tasks'
    | '/executive'
    | '/exports'
    | '/forecast'
    | '/heatmap'
    | '/intelligence'
    | '/manager'
    | '/my-day'
    | '/notifications'
    | '/onboarding'
    | '/planning'
    | '/planning-suggestions'
    | '/reports'
    | '/sync'
    | '/tasks'
    | '/today'
    | '/workload'
    | '/configure/automations'
    | '/configure/new'
    | '/settings/notifications'
    | '/settings/operations'
    | '/api/storage/file'
    | '/api/storage/upload'
    | '/api/public/hooks/adoption-rollup'
    | '/api/public/hooks/automation-due-enqueue'
    | '/api/public/hooks/automation-tick'
    | '/api/public/hooks/carry-forward'
    | '/api/public/hooks/detect-risks'
    | '/api/public/hooks/evening-digest'
    | '/api/public/hooks/generate-nudges'
    | '/api/public/hooks/morning-digest'
    | '/api/public/hooks/planning-suggestions'
    | '/api/public/hooks/workload-snapshot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/analytics'
    | '/blockers'
    | '/command'
    | '/configure'
    | '/dashboard'
    | '/eod'
    | '/eod-tasks'
    | '/executive'
    | '/exports'
    | '/forecast'
    | '/heatmap'
    | '/intelligence'
    | '/manager'
    | '/my-day'
    | '/notifications'
    | '/onboarding'
    | '/planning'
    | '/planning-suggestions'
    | '/reports'
    | '/sync'
    | '/tasks'
    | '/today'
    | '/workload'
    | '/configure/automations'
    | '/configure/new'
    | '/settings/notifications'
    | '/settings/operations'
    | '/api/storage/file'
    | '/api/storage/upload'
    | '/api/public/hooks/adoption-rollup'
    | '/api/public/hooks/automation-due-enqueue'
    | '/api/public/hooks/automation-tick'
    | '/api/public/hooks/carry-forward'
    | '/api/public/hooks/detect-risks'
    | '/api/public/hooks/evening-digest'
    | '/api/public/hooks/generate-nudges'
    | '/api/public/hooks/morning-digest'
    | '/api/public/hooks/planning-suggestions'
    | '/api/public/hooks/workload-snapshot'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/blockers'
    | '/_authenticated/command'
    | '/_authenticated/configure'
    | '/_authenticated/dashboard'
    | '/_authenticated/eod'
    | '/_authenticated/eod-tasks'
    | '/_authenticated/executive'
    | '/_authenticated/exports'
    | '/_authenticated/forecast'
    | '/_authenticated/heatmap'
    | '/_authenticated/intelligence'
    | '/_authenticated/manager'
    | '/_authenticated/my-day'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/planning'
    | '/_authenticated/planning-suggestions'
    | '/_authenticated/reports'
    | '/_authenticated/sync'
    | '/_authenticated/tasks'
    | '/_authenticated/today'
    | '/_authenticated/workload'
    | '/_authenticated/configure/automations'
    | '/_authenticated/configure/new'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/operations'
    | '/api/storage/file'
    | '/api/storage/upload'
    | '/api/public/hooks/adoption-rollup'
    | '/api/public/hooks/automation-due-enqueue'
    | '/api/public/hooks/automation-tick'
    | '/api/public/hooks/carry-forward'
    | '/api/public/hooks/detect-risks'
    | '/api/public/hooks/evening-digest'
    | '/api/public/hooks/generate-nudges'
    | '/api/public/hooks/morning-digest'
    | '/api/public/hooks/planning-suggestions'
    | '/api/public/hooks/workload-snapshot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiStorageFileRoute: typeof ApiStorageFileRoute
  ApiStorageUploadRoute: typeof ApiStorageUploadRoute
  ApiPublicHooksAdoptionRollupRoute: typeof ApiPublicHooksAdoptionRollupRoute
  ApiPublicHooksAutomationDueEnqueueRoute: typeof ApiPublicHooksAutomationDueEnqueueRoute
  ApiPublicHooksAutomationTickRoute: typeof ApiPublicHooksAutomationTickRoute
  ApiPublicHooksCarryForwardRoute: typeof ApiPublicHooksCarryForwardRoute
  ApiPublicHooksDetectRisksRoute: typeof ApiPublicHooksDetectRisksRoute
  ApiPublicHooksEveningDigestRoute: typeof ApiPublicHooksEveningDigestRoute
  ApiPublicHooksGenerateNudgesRoute: typeof ApiPublicHooksGenerateNudgesRoute
  ApiPublicHooksMorningDigestRoute: typeof ApiPublicHooksMorningDigestRoute
  ApiPublicHooksPlanningSuggestionsRoute: typeof ApiPublicHooksPlanningSuggestionsRoute
  ApiPublicHooksWorkloadSnapshotRoute: typeof ApiPublicHooksWorkloadSnapshotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workload': {
      id: '/_authenticated/workload'
      path: '/workload'
      fullPath: '/workload'
      preLoaderRoute: typeof AuthenticatedWorkloadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sync': {
      id: '/_authenticated/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof AuthenticatedSyncRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planning-suggestions': {
      id: '/_authenticated/planning-suggestions'
      path: '/planning-suggestions'
      fullPath: '/planning-suggestions'
      preLoaderRoute: typeof AuthenticatedPlanningSuggestionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planning': {
      id: '/_authenticated/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AuthenticatedPlanningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-day': {
      id: '/_authenticated/my-day'
      path: '/my-day'
      fullPath: '/my-day'
      preLoaderRoute: typeof AuthenticatedMyDayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/intelligence': {
      id: '/_authenticated/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/heatmap': {
      id: '/_authenticated/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof AuthenticatedHeatmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forecast': {
      id: '/_authenticated/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof AuthenticatedForecastRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exports': {
      id: '/_authenticated/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AuthenticatedExportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/executive': {
      id: '/_authenticated/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof AuthenticatedExecutiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eod-tasks': {
      id: '/_authenticated/eod-tasks'
      path: '/eod-tasks'
      fullPath: '/eod-tasks'
      preLoaderRoute: typeof AuthenticatedEodTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eod': {
      id: '/_authenticated/eod'
      path: '/eod'
      fullPath: '/eod'
      preLoaderRoute: typeof AuthenticatedEodRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure': {
      id: '/_authenticated/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof AuthenticatedConfigureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command': {
      id: '/_authenticated/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof AuthenticatedCommandRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blockers': {
      id: '/_authenticated/blockers'
      path: '/blockers'
      fullPath: '/blockers'
      preLoaderRoute: typeof AuthenticatedBlockersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/file': {
      id: '/api/storage/file'
      path: '/api/storage/file'
      fullPath: '/api/storage/file'
      preLoaderRoute: typeof ApiStorageFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/operations': {
      id: '/_authenticated/settings/operations'
      path: '/settings/operations'
      fullPath: '/settings/operations'
      preLoaderRoute: typeof AuthenticatedSettingsOperationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configure/new': {
      id: '/_authenticated/configure/new'
      path: '/new'
      fullPath: '/configure/new'
      preLoaderRoute: typeof AuthenticatedConfigureNewRouteImport
      parentRoute: typeof AuthenticatedConfigureRoute
    }
    '/_authenticated/configure/automations': {
      id: '/_authenticated/configure/automations'
      path: '/automations'
      fullPath: '/configure/automations'
      preLoaderRoute: typeof AuthenticatedConfigureAutomationsRouteImport
      parentRoute: typeof AuthenticatedConfigureRoute
    }
    '/api/public/hooks/workload-snapshot': {
      id: '/api/public/hooks/workload-snapshot'
      path: '/api/public/hooks/workload-snapshot'
      fullPath: '/api/public/hooks/workload-snapshot'
      preLoaderRoute: typeof ApiPublicHooksWorkloadSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/planning-suggestions': {
      id: '/api/public/hooks/planning-suggestions'
      path: '/api/public/hooks/planning-suggestions'
      fullPath: '/api/public/hooks/planning-suggestions'
      preLoaderRoute: typeof ApiPublicHooksPlanningSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/morning-digest': {
      id: '/api/public/hooks/morning-digest'
      path: '/api/public/hooks/morning-digest'
      fullPath: '/api/public/hooks/morning-digest'
      preLoaderRoute: typeof ApiPublicHooksMorningDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-nudges': {
      id: '/api/public/hooks/generate-nudges'
      path: '/api/public/hooks/generate-nudges'
      fullPath: '/api/public/hooks/generate-nudges'
      preLoaderRoute: typeof ApiPublicHooksGenerateNudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/evening-digest': {
      id: '/api/public/hooks/evening-digest'
      path: '/api/public/hooks/evening-digest'
      fullPath: '/api/public/hooks/evening-digest'
      preLoaderRoute: typeof ApiPublicHooksEveningDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/detect-risks': {
      id: '/api/public/hooks/detect-risks'
      path: '/api/public/hooks/detect-risks'
      fullPath: '/api/public/hooks/detect-risks'
      preLoaderRoute: typeof ApiPublicHooksDetectRisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/carry-forward': {
      id: '/api/public/hooks/carry-forward'
      path: '/api/public/hooks/carry-forward'
      fullPath: '/api/public/hooks/carry-forward'
      preLoaderRoute: typeof ApiPublicHooksCarryForwardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/automation-tick': {
      id: '/api/public/hooks/automation-tick'
      path: '/api/public/hooks/automation-tick'
      fullPath: '/api/public/hooks/automation-tick'
      preLoaderRoute: typeof ApiPublicHooksAutomationTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/automation-due-enqueue': {
      id: '/api/public/hooks/automation-due-enqueue'
      path: '/api/public/hooks/automation-due-enqueue'
      fullPath: '/api/public/hooks/automation-due-enqueue'
      preLoaderRoute: typeof ApiPublicHooksAutomationDueEnqueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/adoption-rollup': {
      id: '/api/public/hooks/adoption-rollup'
      path: '/api/public/hooks/adoption-rollup'
      fullPath: '/api/public/hooks/adoption-rollup'
      preLoaderRoute: typeof ApiPublicHooksAdoptionRollupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedConfigureRouteChildren {
  AuthenticatedConfigureAutomationsRoute: typeof AuthenticatedConfigureAutomationsRoute
  AuthenticatedConfigureNewRoute: typeof AuthenticatedConfigureNewRoute
}

const AuthenticatedConfigureRouteChildren: AuthenticatedConfigureRouteChildren =
  {
    AuthenticatedConfigureAutomationsRoute:
      AuthenticatedConfigureAutomationsRoute,
    AuthenticatedConfigureNewRoute: AuthenticatedConfigureNewRoute,
  }

const AuthenticatedConfigureRouteWithChildren =
  AuthenticatedConfigureRoute._addFileChildren(
    AuthenticatedConfigureRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBlockersRoute: typeof AuthenticatedBlockersRoute
  AuthenticatedCommandRoute: typeof AuthenticatedCommandRoute
  AuthenticatedConfigureRoute: typeof AuthenticatedConfigureRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEodRoute: typeof AuthenticatedEodRoute
  AuthenticatedEodTasksRoute: typeof AuthenticatedEodTasksRoute
  AuthenticatedExecutiveRoute: typeof AuthenticatedExecutiveRoute
  AuthenticatedExportsRoute: typeof AuthenticatedExportsRoute
  AuthenticatedForecastRoute: typeof AuthenticatedForecastRoute
  AuthenticatedHeatmapRoute: typeof AuthenticatedHeatmapRoute
  AuthenticatedIntelligenceRoute: typeof AuthenticatedIntelligenceRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRoute
  AuthenticatedMyDayRoute: typeof AuthenticatedMyDayRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlanningRoute: typeof AuthenticatedPlanningRoute
  AuthenticatedPlanningSuggestionsRoute: typeof AuthenticatedPlanningSuggestionsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSyncRoute: typeof AuthenticatedSyncRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedWorkloadRoute: typeof AuthenticatedWorkloadRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsOperationsRoute: typeof AuthenticatedSettingsOperationsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBlockersRoute: AuthenticatedBlockersRoute,
  AuthenticatedCommandRoute: AuthenticatedCommandRoute,
  AuthenticatedConfigureRoute: AuthenticatedConfigureRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEodRoute: AuthenticatedEodRoute,
  AuthenticatedEodTasksRoute: AuthenticatedEodTasksRoute,
  AuthenticatedExecutiveRoute: AuthenticatedExecutiveRoute,
  AuthenticatedExportsRoute: AuthenticatedExportsRoute,
  AuthenticatedForecastRoute: AuthenticatedForecastRoute,
  AuthenticatedHeatmapRoute: AuthenticatedHeatmapRoute,
  AuthenticatedIntelligenceRoute: AuthenticatedIntelligenceRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRoute,
  AuthenticatedMyDayRoute: AuthenticatedMyDayRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlanningRoute: AuthenticatedPlanningRoute,
  AuthenticatedPlanningSuggestionsRoute: AuthenticatedPlanningSuggestionsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSyncRoute: AuthenticatedSyncRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedWorkloadRoute: AuthenticatedWorkloadRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsOperationsRoute: AuthenticatedSettingsOperationsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiStorageFileRoute: ApiStorageFileRoute,
  ApiStorageUploadRoute: ApiStorageUploadRoute,
  ApiPublicHooksAdoptionRollupRoute: ApiPublicHooksAdoptionRollupRoute,
  ApiPublicHooksAutomationDueEnqueueRoute:
    ApiPublicHooksAutomationDueEnqueueRoute,
  ApiPublicHooksAutomationTickRoute: ApiPublicHooksAutomationTickRoute,
  ApiPublicHooksCarryForwardRoute: ApiPublicHooksCarryForwardRoute,
  ApiPublicHooksDetectRisksRoute: ApiPublicHooksDetectRisksRoute,
  ApiPublicHooksEveningDigestRoute: ApiPublicHooksEveningDigestRoute,
  ApiPublicHooksGenerateNudgesRoute: ApiPublicHooksGenerateNudgesRoute,
  ApiPublicHooksMorningDigestRoute: ApiPublicHooksMorningDigestRoute,
  ApiPublicHooksPlanningSuggestionsRoute:
    ApiPublicHooksPlanningSuggestionsRoute,
  ApiPublicHooksWorkloadSnapshotRoute: ApiPublicHooksWorkloadSnapshotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
